# Generated by Django 5.0 on 2023-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ip', models.CharField(max_length=500)),
                ('request_data', models.CharField(max_length=500)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
