# Generated by Django 5.0 on 2023-12-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('freelancer', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custcommentfreel',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_comments_c', to='freelancer.freelancer'),
        ),
        migrations.AddField(
            model_name='custcommentorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_comments_o', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custcommentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_comments_o', to='order.order'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_freelancers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='freelancer.freelancer'),
        ),
        migrations.AddField(
            model_name='freelancerrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerrating',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='freelancer.freelancer'),
        ),
        migrations.AddField(
            model_name='freelcommentcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_comments_f', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelcommentcustomer',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_comments_f', to='freelancer.freelancer'),
        ),
        migrations.AddField(
            model_name='freelcommentorder',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_comments_o', to='freelancer.freelancer'),
        ),
        migrations.AddField(
            model_name='freelcommentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_comments_o', to='order.order'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('freelancer', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='freelancerrating',
            unique_together={('freelancer', 'customer')},
        ),
    ]
